darkborder = "#D4C0A1"
lightborder = "#F1E0C6"
vdarkborder = "#505050"

; List: newcomer,gallery,premium,poll,highscores,networks - discord,donate,searchchar,rashid
boxes = "rank,discord,serversave,donate,searchchar,rashid,poll"

background_image = "arise-red-fortress.png"
logo_image = "logo-eclipse-transparent.png"
gallery_image_id_from_database = 1
