-- Adds duo donation orders and reward tracking for Eclipse OT.
-- Apply with: mysql canary < sql/015-add-duo-donations.sql

CREATE TABLE IF NOT EXISTS eclipse_duo_donation_orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  payer_account_id INT(11) UNSIGNED NOT NULL,
  payer_player_id INT(11) NOT NULL,
  partner_account_id INT(11) UNSIGNED NOT NULL,
  partner_player_id INT(11) NOT NULL,
  package_key VARCHAR(50) NOT NULL,
  amount_brl_cents INT(11) UNSIGNED NOT NULL,
  total_coins INT(11) UNSIGNED NOT NULL,
  payer_coins INT(11) UNSIGNED NOT NULL,
  partner_coins INT(11) UNSIGNED NOT NULL,
  outfit_key VARCHAR(80) NOT NULL,
  outfit_name VARCHAR(120) NOT NULL,
  male_looktype INT(11) UNSIGNED NOT NULL,
  female_looktype INT(11) UNSIGNED NOT NULL,
  outfit_addon TINYINT(3) UNSIGNED NOT NULL DEFAULT 3,
  boost_seconds INT(11) UNSIGNED NOT NULL DEFAULT 7200,
  boost_percent TINYINT(3) UNSIGNED NOT NULL DEFAULT 50,
  status VARCHAR(40) NOT NULL DEFAULT 'pending_partner',
  partner_token CHAR(64) NOT NULL,
  partner_accepted_at DATETIME DEFAULT NULL,
  donation_intent_id BIGINT UNSIGNED DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT NULL,
  confirmed_at DATETIME DEFAULT NULL,
  applied_at DATETIME DEFAULT NULL,
  expires_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY eclipse_duo_partner_token_uq (partner_token),
  KEY eclipse_duo_payer_idx (payer_account_id),
  KEY eclipse_duo_partner_idx (partner_account_id),
  KEY eclipse_duo_intent_idx (donation_intent_id),
  KEY eclipse_duo_status_idx (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS eclipse_duo_donation_rewards (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  account_id INT(11) UNSIGNED NOT NULL,
  player_id INT(11) NOT NULL,
  reward_type VARCHAR(30) NOT NULL,
  amount INT(11) UNSIGNED DEFAULT NULL,
  outfit_name VARCHAR(120) DEFAULT NULL,
  male_looktype INT(11) UNSIGNED DEFAULT NULL,
  female_looktype INT(11) UNSIGNED DEFAULT NULL,
  outfit_addon TINYINT(3) UNSIGNED DEFAULT NULL,
  boost_seconds INT(11) UNSIGNED DEFAULT NULL,
  boost_percent TINYINT(3) UNSIGNED DEFAULT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'pending',
  applied_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  notes VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY eclipse_duo_rewards_order_idx (order_id),
  KEY eclipse_duo_rewards_account_idx (account_id),
  KEY eclipse_duo_rewards_player_idx (player_id),
  KEY eclipse_duo_rewards_status_idx (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
